model_list:
  - model_name: meta-llama/Llama-3.2-1B
    litellm_params:
      model: openai/meta-llama/Llama-3.2-1B
      api_base: http://localhost:8001/v1
      api_key: dummy
      max_input_tokens: 4096
      max_output_tokens: 4096

  - model_name: meta-llama/Meta-Llama-3-8B
    litellm_params:
      model: openai/meta-llama/Meta-Llama-3-8B
      api_base: http://localhost:8002/v1
      api_key: dummy
      max_input_tokens: 4096
      max_output_tokens: 4096
